### PR TITLE
Feature/api doc

### LINKED ISSUE #23: add apiDoc to signsfive-api
can use npm supported - http://apidocjs.com/#getting-started

### PR DESCRIPTION
**Pull request by kratsg**
This resolves #23. This will need to be dealt with around same time as #22 .

### CODE REVIEW

**Review by meltedspork — APPROVED** [review]

**Comment by kratsg** [comment]
I thought we were going OpenAPI and not apiDoc?

**Comment by meltedspork** [comment]
ahh sorry - i misunderstood the doc was for. thought it was similar to `jsDoc` but yeah you are right. We can switch to jsDoc which makes more sense - thanks!!

**Comment by kratsg** [comment]
> ahh sorry - i misunderstood the doc was for. thought it was similar to jsDoc but yeah you are right. We can switch to jsDoc which makes more sense - thanks!!
> 
>  Delete branch

No, I'm now even more confused. We're using OpenAPI instead of apiDoc.

**Comment by meltedspork** [comment]
Yeah OpenAPI is to _document_ the _endpoints_ . JsDoc is to _document_ the _methods/functionalities_ in the codebase.

**Pull request closed without merging**
